### ISSUE TITLE
fails to generate report

### ISSUE THREAD

**Issue by wolverineks** [davityavryan/yarn-audit-html#29]
```bash
Failed to generate report! Please report this issue to https://github.com/davityavryan/yarn-audit-html/issues
 TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at generateReport (/Users/kevinsullivan/.config/yarn/global/node_modules/yarn-audit-html/lib/reporter.js:67:37)
    at Socket.<anonymous> (/Users/kevinsullivan/.config/yarn/global/node_modules/yarn-audit-html/index.js:62:9)
    at Socket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[1]    71504 abort      yarn audit --json |
       71505 done       yarn-audit-html
```

**Comment by wolverineks** [comment]
looks like this worked https://github.com/davityavryan/yarn-audit-html/issues/28#issuecomment-860132028

**Comment by davityavryan** [comment]
@wolverineks does your report contain too much vulnerabilities?

**Comment by wolverineks** [comment]
5360 vulnerabilities found - Packages audited: 3077

**Comment by davityavryan** [comment]
oh...
glad that my tool helped at least.

**Comment by wolverineks** [comment]
yep....
