### ISSUE TITLE
Fails to create HTML report with v4.0.0

### ISSUE THREAD

**Issue by rdepke** [davityavryan/yarn-audit-html#45]
After updating to the latest version the generation of the html report fails. With the following error.
`{"type":"warning","data":"../../../package.json: No license field"}
{"type":"error","data":"Couldn't find any versions for \"@webassemblyjs/helper-numbers\" that matches \"1.11.3\""}
Error: Couldn't find any versions for "@webassemblyjs/helper-wasm-bytecode" that matches "1.11.3"
    at MessageError.ExtendableBuiltin (/builds/PROJECTNAME/PROJECTNAME-owasp-check/node/yarn/dist/lib/cli.js:721:66)
    at new MessageError (/builds/PROJECTNAME/PROJECTNAME-owasp-check/node/yarn/dist/lib/cli.js:750:123)
    at Function.<anonymous> (/builds/PROJECTNAME/PROJECTNAME-owasp-check/node/yarn/dist/lib/cli.js:50351:13)
    at Generator.next (<anonymous>)
    at step (/builds/PROJECTNAME/PROJECTNAME-owasp-check/node/yarn/dist/lib/cli.js:310:30)
    at /builds/PROJECTNAME/PROJECTNAME-owasp-check/node/yarn/dist/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Checking audit logs...
Failed to generate report! Please report this issue to https://github.com/davityavryan/yarn-audit-html/issues
 TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at generateReport (/builds/PROJECTNAME/PROJECTNAME-owasp-check/node_modules/yarn-audit-html/lib/reporter.js:68:41)
    at Socket.<anonymous> (/builds/PROJECTNAME/PROJECTNAME-owasp-check/node_modules/yarn-audit-html/index.js:62:9)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

**Comment by davityavryan** [comment]
Hi @rdepke,
Please provide package.json and yarn.lock if possible. if it contains sensitive information, please remove it.
If you don't want to share because of any reasons, just send me your node, yarn version and output of `yarn audit --json`.
Thanks in advance ;)

**Comment by davityavryan** [comment]
Seems like it is not an issue of this package. It’s just `@webassemblyjs/helper-numbers` does not have version 1.11.3 see [this](https://www.npmjs.com/package/@webassemblyjs/helper-numbers?activeTab=versions) link.
Maybe they did remove it.
Closing.
